<B>TENSORFLOW is framework for neural networks.<B>

In [64]:
# importing tensorflow
import tensorflow as tf
print('Latest Version Of TensorFlow :', tf.__version__)

Latest Version Of TensorFlow : 1.13.1


In [48]:
# constants in tensorflow
hello_msg = tf.constant("Hello")
world_msg = tf.constant("World")
print(hello_msg, world_msg)
# it will print type and number of times it gets executed

Tensor("Const_38:0", shape=(), dtype=string) Tensor("Const_39:0", shape=(), dtype=string)


In [49]:
# creating sessions
sess = tf.Session()
result = sess.run(hello_msg+world_msg)
print(result)

b'HelloWorld'


In [50]:
# adding two number
num_1 = tf.constant(30)
num_2 = tf.constant(20)
print(sess.run(num_1+num_2))
# printing addition of two number

50


In [51]:
# creating constant
const = tf.constant(50)

# creating matrix
matrix = tf.fill((5, 5), 10)

# creating zero matrix
zeros = tf.zeros((5, 5))

# creating ones matrix
ones = tf.ones((5, 5))

# creating normal random number
rand_normal = tf.random_normal((5, 5), mean=0, stddev=1.0)

# creating uniform random number
rand_uniform = tf.random_uniform((5, 5), minval=0, maxval=1)

In [52]:
# storing all these in a list
my_ops = [const, matrix, zeros, ones, rand_normal, rand_uniform]

# printing all the values using interactive session
sess = tf.InteractiveSession()
for op in my_ops:
    print(sess.run(op), '\n')

50 

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[ 0.72620076  0.55799747 -1.071955    1.6124803   0.6486945 ]
 [-0.3972331  -0.91477966  2.0095208   2.0586572  -0.8646025 ]
 [-1.0094838   0.8284096   1.5198699   0.43955606 -0.53661   ]
 [-0.5786599   0.18367922  0.4231522  -1.0018035   0.8040901 ]
 [-0.7081377   1.428712    0.15139827  0.6869401  -0.8872181 ]] 

[[0.5947547  0.6374872  0.8814709  0.93572724 0.5373421 ]
 [0.39167047 0.65253806 0.00268316 0.24993455 0.33792543]
 [0.89950264 0.52083516 0.6723589  0.72520185 0.33574057]
 [0.81035686 0.12462986 0.38780463 0.17089903 0.8631289 ]
 [0.73965645 0.41716278 0.6571119  0.36525714 0.5863888 ]] 



In [53]:
# eval method for printing
for op in my_ops:
    print(op.eval(), '\n')
# same output as above

# closing session
sess.close()

50 

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[-0.00692973  0.9036652   0.08345085 -0.48711884  0.36867094]
 [ 0.10991668  0.45705023 -0.9448428  -0.5124498   0.1672232 ]
 [ 1.0433977   0.5093578  -0.6056914   1.2643964   0.3353032 ]
 [ 1.4839929   0.4615967   0.11373381 -1.8238255   1.4719492 ]
 [-1.3920562  -0.5853498   0.08097904  1.9111977  -1.6687627 ]] 

[[0.97105515 0.9036578  0.11032939 0.07761061 0.37563086]
 [0.80000556 0.5368277  0.45164096 0.8421571  0.0372839 ]
 [0.42081285 0.5704504  0.7534963  0.51646626 0.17272723]
 [0.9295032  0.9926239  0.26440787 0.68124354 0.8117119 ]
 [0.48357153 0.1717695  0.37065208 0.62691855 0.4103763 ]] 



In [56]:
# matrix multiplication in tensor
m_1 = tf.constant([[1, 2], [3, 4]])
m_2 = tf.constant([[10], [100]])
print(m_1.get_shape)
print(m_2.get_shape, '\n')

# multiplying using matmul()
result = tf.matmul(m_1, m_2)
sess = tf.InteractiveSession()
print(sess.run(result))

# location of default graph in memory
print(tf.get_default_graph)
# closing session
sess.close()

<bound method Tensor.get_shape of <tf.Tensor 'Const_47:0' shape=(2, 2) dtype=int32>>
<bound method Tensor.get_shape of <tf.Tensor 'Const_48:0' shape=(2, 1) dtype=int32>> 

[[210]
 [430]]
<function get_default_graph at 0x0000000007713D90>


In [62]:
# graphs in tensor which gets created in backend
graph_1 = tf.Graph()
print(graph_1)

# making graph_1 it as default graph 
graph_1 = tf.get_default_graph()
print(graph_1)